### ISSUE TITLE
Update circuit until the values are stable

### ISSUE THREAD

**Issue by dopsi** [hellow554/logical-rs#3]
I am working on a code which does look at the outputs of a circuit, but I'm only interested in getting the results once the circuit has stabilized.

To achieve this, I see two options: add a return value to the `update()` function from the `Updateable` trait (this function could return true if a value changed and false otherwise) and add the same return value to the `tick()` function from the `Circuit` struct (which would return true if one of the updaters returned true).

This way, the `Circuit` could be used like this:

```rust
let mut circuit = Circuit::default();
/* Configure updaters */

let mut timeout = 0_u32;
while circuit.tick() && timeout < 100 { // 100 is a arbitrary value, to avoid looping if we have an oscillating circuit
    timeout += 1;
}
```
If you would accept this feature, I'm willing to implement it (or if you see a better way of doing it, I'd be glad to do that too).

**Comment by hellow554** [comment]
Thanks for the issue!

How would you implement the bool return value on `circuit.tick()`?

https://github.com/hellow554/logical-rs/blob/9bf9bc30f1f5eb37d73db4aa9623201364225748/src/circuit.rs#L9-L12

Would you return true if one of the updateables returned true? If all? 

Changing the trait should be doable. I think we can do it for now, I'll happily accept a PR, afer resolving the question above.

**Comment by dopsi** [comment]
> Would you return true if one of the updateables returned true? If all?

I thought about returning true for just one, but another option would be to return the number of changed values (i.e. the number of updaters that changed value).

**Comment by hellow554** [comment]
> but another option would be to return the number of changed values 

I don't know why, but I don't feel like that would be a good idea. Not sure though.

But returning true if any of the updater returns true seems good.

I don't care if you use `let result = false; for [ ... ] { result |= u.update() }` or `fold` to achieve the behavoir. That's up to you. 
It would be good, if you could update the examples as well, but I'm willing to do that if you don't have time.
Anyway, thanks for the feedback and I wait for your PR :)

**Comment by hellow554** [comment]
Closed by https://github.com/hellow554/logical-rs/pull/6
